### ISSUE TITLE
ESLint's no-undef for tw as undefined variable

### ISSUE THREAD

**Issue by deden** [andrewdelprete/babel-plugin-tailwind#5]
Hi,
Thanks for this great plugin!
Unfortunately, Travis build failed when I try to make a new PR, with error 'tw' is not defined  no-undef.

Do you think is it possible to provide a more elegant way to pass this test? I would prefer not to disable the no-undef rule for eslint.

**Comment by deden** [comment]
No problem, here's what I did in [#218](https://github.com/nozzle/react-static/pull/218) :
.eslintrc.js
<pre><code>module.exports = {
  extends: 'react-tools',
  globals: {
  	'tw': true,
  }
}</code></pre>

**Comment by andrewdelprete** [comment]
Hey @deden, I must have missed this issue somehow. Yeah what you did looks good. I may adjust the plugin later to have a runtime version you import and then just compile it away at build time.
